name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set execute permission for deploy.sh
      run: chmod +x /home/ubuntu/demo-repo/deploy.sh

    - name: Deploy application
      run: |
        cd /home/ubuntu/demo-repo
        git pull origin main
        ./deploy.sh
